#Workflow
name: First Workflow
on: workflow_dispatch 
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        #We are defining the command that will be executed in cmd line. 
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"

